### ISSUE TITLE
Switch to use Path API

### ISSUE THREAD

**Issue by bhillmann** [shipt/opsml#156]
### Description

Currently, [this](https://github.com/shipt/opsml/blob/f8df6fee53fb76ef8971816adee17cf42ff65ddb/opsml/projects/mlflow/_active_run.py#L127) code uses the fragile split on "/" and causes bugs if we pass in a `Pathlike` object. Can we switch it to use the `Path` library API?

**Comment by thorrester** [comment]
Hey @bhillmann - great suggestion! For my own knowledge, are you proposing that the function signature accept a `string` or `Path` object?

e.g. 

```python
def log_artifact_from_file(self, local_path: Union[Path, str], artifact_path: Optional[str] = None) -> None:
     ...
     # something like this
     filename = local_path.name if isinstance(local_path, Path) else Path(local_path).name
```

**Comment by bhillmann** [comment]
Yes, that is what I am suggesting, except I would use the signature as suggested by [PEP 519](https://peps.python.org/pep-0519/#provide-specific-type-hinting-support).

```python
def log_artifact_from_file(self, local_path: Union[str, os.PathLike], artifact_path: Optional[Union[str, os.PathLike]] = None) -> None:
     ...
     # something like this
     filename = local_path.name if isinstance(local_path, Path) else Path(local_path).name
```

**Comment by thorrester** [comment]
We could add the ability to add pathlike to `artifact_path`; however, it just seems like extra work on the user since artifact path is only meant to specify an explicit `dir` you'd like to save the artifact to under the `misc` parent dir. So it would be decoded to a string anyway. Having `PathLike` in `local_path` makes sense since we actually need to extract information from the local path.
